version: "3.7"
services: 
    redis1:
        image: redis:latest
        container_name: redis1
        command: /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf"
        environment:
            REDIS_PASSWORD: 123456
        ports:
        - 6376:6379
        volumes:
        - type: bind
          source: /root/redis-cluster/redis
          target: /usr/local/etc/redis
        networks:
          redis-cluster-net:
            ipv4_address: 192.168.88.81
    redis2:
        image: redis:latest
        container_name: redis2
        command: /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf"
        environment:
            REDIS_PASSWORD: 123456
        ports:
        - 6377:6379
        volumes:
        - type: bind
          source: /root/redis-cluster/redis
          target: /usr/local/etc/redis
        networks:
          redis-cluster-net:
            ipv4_address: 192.168.88.82
    redis3:
        image: redis:latest
        container_name: redis3
        command: /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf"
        environment:
            REDIS_PASSWORD: 123456
        ports:
        - 6378:6379
        volumes:
        - type: bind
          source: /root/redis-cluster/redis
          target: /usr/local/etc/redis
        networks:
          redis-cluster-net:
            ipv4_address: 192.168.88.83
    redis4:
        image: redis:latest
        container_name: redis4
        command: /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf"
        environment:
            REDIS_PASSWORD: 123456
        ports:
        - 6373:6379
        volumes:
        - type: bind
          source: /root/redis-cluster/redis
          target: /usr/local/etc/redis
        networks:
          redis-cluster-net:
            ipv4_address: 192.168.88.84
    redis5:
        image: redis:latest
        container_name: redis5
        command: /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf"
        environment:
            REDIS_PASSWORD: 123456
        ports:
        - 6374:6379
        volumes:
        - type: bind
          source: /root/redis-cluster/redis
          target: /usr/local/etc/redis
        networks:
          redis-cluster-net:
            ipv4_address: 192.168.88.85
    redis6:
        image: redis:latest
        container_name: redis6
        command: /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf"
        environment:
            REDIS_PASSWORD: 123456
        ports:
        - 6375:6379
        volumes:
        - type: bind
          source: /root/redis-cluster/redis
          target: /usr/local/etc/redis
        networks:
          redis-cluster-net:
            ipv4_address: 192.168.88.86
networks:
    redis-cluster-net:
        external: true
        name: redis-cluster-net