version: "3.7"
services: 
    redis1:
        image: redis:latest
        container_name: redis1
        command: /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf"
        environment:
            REDIS_PASSWORD: 123456
        ports:
        - 6376:6379
        volumes:
        - type: bind
          source: /root/redis-cluster/redis
          target: /usr/local/etc/redis
        networks:
          redis-cluster-net:
            ipv4_address: 192.168.88.81
    redis2:
        image: redis:latest
        container_name: redis2
        command: /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf --replicaof 192.168.88.81 6379"
        depends_on:
        - redis1
        environment:
            REDIS_PASSWORD: 123456
        ports:
        - 6377:6379
        volumes:
        - type: bind
          source: /root/redis-cluster/redis
          target: /usr/local/etc/redis
        networks:
          redis-cluster-net:
            ipv4_address: 192.168.88.82
    redis3:
        image: redis:latest
        container_name: redis3
        command: /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf --replicaof 192.168.88.81 6379"
        depends_on:
        - redis1
        environment:
            REDIS_PASSWORD: 123456
        ports:
        - 6378:6379
        volumes:
        - type: bind
          source: /root/redis-cluster/redis
          target: /usr/local/etc/redis
        networks:
          redis-cluster-net:
            ipv4_address: 192.168.88.83
networks:
    redis-cluster-net:
        external: true
        name: redis-cluster-net