version: "3.7"
services: 
    redis1:
        image: redis:latest
        container_name: redis1
        command: /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf"
        ports:
        - 6376:6379
        volumes:
        - type: bind
          source: /opt/docker-compose/redis-sentinel
          target: /usr/local/etc/redis
        - type: bind
          source: /var/lib/docker-redis/redis1
          target: /data/
        networks:
          redis-cluster-net:
            ipv4_address: 172.28.5.11
    redis2:
        image: redis:latest
        container_name: redis2
        command: /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf --replicaof 172.28.5.11 6379"
        depends_on:
        - redis1
        ports:
        - 6377:6379
        volumes:
        - type: bind
          source: /opt/docker-compose/redis-sentinel
          target: /usr/local/etc/redis
        - type: bind
          source: /var/lib/docker-redis/redis2
          target: /data/
        networks:
          redis-cluster-net:
            ipv4_address: 172.28.5.12
    redis3:
        image: redis:latest
        container_name: redis3
        command: /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf --replicaof 172.28.5.11 6379"
        depends_on:
        - redis1
        ports:
        - 6378:6379
        volumes:
        - type: bind
          source: /opt/docker-compose/redis-sentinel
          target: /usr/local/etc/redis
        - type: bind
          source: /var/lib/docker-redis/redis3
          target: /data/
        networks:
          redis-cluster-net:
            ipv4_address: 172.28.5.13
    redis-sentinel1:
        image: redis:latest
        container_name: redis-sentinel1
        command: /bin/bash -c "redis-sentinel /usr/local/etc/redis/redis-sentinel.conf"
        depends_on:
        - redis1
        - redis2
        - redis3
        ports:
        - 6373:6379
        volumes:
        - type: bind
          source: /opt/docker-compose/redis-sentinel
          target: /usr/local/etc/redis
        networks:
          redis-cluster-net:
            ipv4_address: 172.28.5.14
    redis-sentinel2:
        image: redis:latest
        container_name: redis-sentinel2
        command: /bin/bash -c "redis-sentinel /usr/local/etc/redis/redis-sentinel.conf"
        depends_on:
        - redis1
        - redis2
        - redis3
        ports:
        - 6374:6379
        volumes:
        - type: bind
          source: /opt/docker-compose/redis-sentinel
          target: /usr/local/etc/redis
        networks:
          redis-cluster-net:
            ipv4_address: 172.28.5.15
    redis-sentinel3:
        image: redis:latest
        container_name: redis-sentinel3
        command: /bin/bash -c "redis-sentinel /usr/local/etc/redis/redis-sentinel.conf"
        depends_on:
        - redis1
        - redis2
        - redis3
        ports:
        - 6375:6379
        volumes:
        - type: bind
          source: /opt/docker-compose/redis-sentinel
          target: /usr/local/etc/redis
        networks:
          redis-cluster-net:
            ipv4_address: 172.28.5.16
networks:
    redis-cluster-net:
        external: true
        name: redis-sentinel-net